README.md, doc/architecture/decisions/0001-use-adr.md, doc/architecture/decisions/0002-spilt-auth-and-prison-api.md, doc/architecture/decisions/9999-end.md
* Added ADR for the reason for this API
* A link from README to the first ADR
* Added links so you can page through the ADRs
Once committed I will link to this ADR from nomis-user-roles-api as well
=> DT-2858 ADR for why this and nomis-user-roles-api exist

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
includes upgrade to springboot 2.6.2
=> DT-3022: upgrade gradle-springboot plugin to 4.0.1

build.gradle.kts
=> HAAR-89: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.2

build.gradle.kts
includes upgrade to spring-boot 2.6.4
=> HAAR-185: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.5-beta

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/config/ManageUsersApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/AuthService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/TokenService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/HmppsAuthMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/NomisApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/TokenServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserServiceTest.kt
=> HAAR-613: Validate email domain

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/AuthService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/HmppsAuthMockServer.kt
=> HAAR-639 : validate email domains

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/AuthService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/TokenService.kt
=> HAAR-639: Added first and last name

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/config/ManageUsersApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/ExternalUsersApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/GroupsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/GroupsServiceTest.kt
=> HAAR-825:Add create group

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/ExternalUsersApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/GroupsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerTest.kt
=> HAAR-826: Create child group

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/ExternalUsersApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/GroupsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/GroupsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/GroupsServiceTest.kt
=> HAAR-821: Added Delete endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/ExternalUsersApiService.kt
=> HAAR-931: fix broken build

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/EmailNotificationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/EmailNotificationService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/EmailNotificationControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/EmailNotificationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/EmailNotificationServiceTest.kt
Send User enable email using gov notification client
=> HAAR-860: Send User enable email using gov notification client

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/ExternalUserSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/ExternalUsersApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserSearchService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/ExternalUserSearchControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserSearchServiceTest.kt
=> HAAR-866: Added search by username

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserRolesApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserRolesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/external/UserRolesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserRolesControllerIntTest.kt
=> HAAR-868: Get searchable roles

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserRolesApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/nomis/NomisUser.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/config/AuthExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/model/AzureUser.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/model/DeliusUser.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/model/GenericUser.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserRolesControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserSearchControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserServiceTest.kt
=> HAAR-885:  Get user roles by username

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/NotificationBannerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/ExternalUsersApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/RolesControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/EmailDomainControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/GroupsControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserGroupControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserSearchControllerIntTest.kt
WIP: Added swagger docs and removed some duplicate stubs
=> HAAR-1233:  Added swagger docs and removed some duplicate stubs

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/auth/AuthApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/integration/wiremock/HmppsAuthMockServer.kt
…source.Amend Auth endpoint for get user details by username and source
=> HAAR-1262:  Amend Auth endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/UserServiceTest.kt
Remove prefix 'REMOVE_' from Delius roles.
=> HAAR-885:  Remove prefix 'REMOVE_' from delius roles.

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/nomis/UserApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/prison/UserController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/prison/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/prison/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/prison/UserControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/prison/UserServiceTest.kt
New branch with all user look up changes.
=> Haar 1411 user details lookup v2

helm_deploy/values-dev.yaml
Add iss-stage (HPA:- https://hpa-stage.hmpps.dsd.io/) IP to allowed list
=> HAAR-1354: Add iss-stage ip to allowed list

helm_deploy/values-dev.yaml
Add iss-stage (HPA:- https://hpa-stage.hmpps.dsd.io/) IPs to allowed list
=> HAAR-1354: Add iss-stage IPs to allow list

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Add iss-preprod and iis-prod (HPA:- https://hpa-preprod.service.hmpps.dsd.io/ and https://hpa.service.hmpps.dsd.io/) IPs to allowed list
=> HAAR-1354: Add iss-preprod and iis-prod IP allowed list

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/WebClientUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/auth/AuthApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/delius/UserApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/EmailDomainApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/GroupsApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/RolesApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserGroupApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserRolesApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/external/UserSearchApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/nomis/RolesApiService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/adapter/nomis/UserApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/external/UserSearchControllerIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/service/delius/UserServiceTest.kt
Parameterize path variables in web client requests
=> HAAR-1965: Parameterize path variables in web client requests

src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/model/PrisonUserSearchSummary.kt
Bring user status in line with nomis user and roles api by making it optional
=> make user status nullable parameter

.gitignore, src/main/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/prison/UserController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/manageusersapi/resource/prison/UserControllerIntTest.kt
Add new search endpoint to find users by activeCaseload and nomisRole
=> Haar 2835 new search endpoint
